version: '3.4'

services:
  blurby:
    image: joniturunen/blurby
    build:
      context: .
      dockerfile: ./Dockerfile
    user: appuser
    environment:
      - BLURBY_DB_FILE=/blurby/data/sqlite.db
      - BLURBY_TTL_HOURS=48
      - BLURBY_THREADS=6
    ports:
      - "8080:8080"
    volumes:
      - ./data:/blurby/data
