version: '3.4'

services:
  blurby:
    image: joniturunen/blurby
    build:
      context: .
      dockerfile: ./Dockerfile
    user: appuser
    environment:
      - BLURBY_DB_FILE=/blurby/data/sqlite.db
    volumes:
      - ./data:/blurby/data
